
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Controller
  arm_base_controller:
    type: position_controllers/JointPositionController
    joint: arm_base_joint

  # Controller
  link_1_controller:
    type: position_controllers/JointPositionController
    joint: link_1_joint

  # Controller
  link_2_controller:
    type: position_controllers/JointPositionController
    joint: link_2_joint

  # Controller
  link_3_controller:
    type: position_controllers/JointPositionController
    joint: link_3_joint

  # Controller
  link_4_controller:
    type: position_controllers/JointPositionController
    joint: link_4_joint

  # Controller
  link_5_controller:
    type: position_controllers/JointPositionController
    joint: link_5_joint
